### ISSUE TITLE
urllib3 v2 incompatibility

### ISSUE THREAD

**Issue by kritus1** [4l1fe/tg-docker-command-bot#1]
I faced the issue "docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'"

This is the fix:
pip uninstall requests
pip install requests==2.28.1

from:
https://github.com/docker/docker-py/issues/3113#issuecomment-1566800805

**Comment by 4l1fe** [comment]
Hey. Thank you. That's not a bag of the bot, but could you show how you run the bot and full error traceback?

The issue link that you attached isn't working.

**Comment by kritus1** [comment]
Hi!  
Yes, it's not a bot's issue, it's related to urllib3.
I was building container according to the Dockerfile, then ./run.py and faced the error. I didn't save the full error traceback, but can recreate and drop it here.

P.S. corrected the link

**Comment by kritus1** [comment]
The error log after /echo command:

```
2023-06-05 08:17:42,715 - root - INFO - Command /echo
2023-06-05 08:17:42,717 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/ubuntu/.local/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "./run.py", line 91, in wrapped_callback
    docker_client = docker.from_env()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: request() got an unexpected keyword argument 'chunked'
```

**Comment by 4l1fe** [comment]
> The error log after /echo command:

Thank you!

**Comment by 4l1fe** [comment]
[Restrict requests version](https://github.com/4l1fe/tg-docker-command-bot/commit/00a7dcab549990bdf27edc14c48a07eb85493594)

**Comment by 4l1fe** [comment]
[Restrict requests version](https://github.com/4l1fe/tg-docker-command-bot/commit/00a7dcab549990bdf27edc14c48a07eb85493594)
